### 行政区划数据集
GET /Administratives HTTP/1.1
Host: {{host}}:{{port}}

### 行政区划数据集
@format = {{$input 格式(plain,keyed) $value:plain }}
GET /Administratives?format={{format}} HTTP/1.1
Host: {{host}}:{{port}}

### 行政区划数据集
@id = {{$input 地址编号(譬如:739180544) $value:739180544 }}
GET /Administratives/{{id}} HTTP/1.1
Host: {{host}}:{{port}}

### 行政区划数据集
@province = {{$input 省市编号(省/州/直辖市) $value: }}
@city = {{$input 市县编号(市县/区) $value: }}
GET /Administratives/{{province}}-{{city}}-0-0 HTTP/1.1
Host: {{host}}:{{port}}

### 行政区划数据集
@province = {{$input 省市编号(省/州/直辖市) $value: }}
@city = {{$input 市县编号(市县/区) $value: }}
@district = {{$input 区镇编号(区镇/乡) $value: }}
GET /Administratives/{{province}}-{{city}}-{{district}}-0 HTTP/1.1
Host: {{host}}:{{port}}

### 行政区划数据集
@province = {{$input 省市编号(省/州/直辖市) $value: }}
@city = {{$input 市县编号(市县/区) $value: }}
@district = {{$input 区镇编号(区镇/乡) $value: }}
@street = {{$input 街道编号(街道/社区/村) $value: }}
GET /Administratives/{{province}}-{{city}}-{{district}}-{{street}} HTTP/1.1
Host: {{host}}:{{port}}

### 行政区划数据集(省级)
GET /Administratives/Provinces HTTP/1.1
Host: {{host}}:{{port}}

### 行政区划数据集(市县级)
@province = {{$input 省市编号(省/州/直辖市) $value: }}
GET /Administratives/{{province}}/Cities HTTP/1.1
Host: {{host}}:{{port}}

### 行政区划数据集(区镇级)
@province = {{$input 省市编号(省/州/直辖市) $value: }}
@city = {{$input 市县编号(市县/区) $value: }}
GET /Administratives/{{province}}-{{city}}/Districts HTTP/1.1
Host: {{host}}:{{port}}

### 行政区划数据集(街道/乡级)
@province = {{$input 省市编号(省/州/直辖市) $value: }}
@city = {{$input 市县编号(市县/区) $value: }}
@district = {{$input 区镇编号(区镇/乡) $value: }}
GET /Administratives/{{province}}-{{city}}-{{district}}/Streets HTTP/1.1
Host: {{host}}:{{port}}
